

/* Create Tables */

CREATE TABLE ICTUSER.BBS
(
	ID number(19,0) NOT NULL,
	TITLE varchar2(50 char) NOT NULL,
	CONTENT varchar2(2000 char) NOT NULL,
	POSTDATE timestamp DEFAULT SYSDATE,
	USERNAME varchar2(200 char) NOT NULL,
	HITCOUNT number(38),
	CONSTRAINT SYS_C007586 PRIMARY KEY (ID)
);


CREATE TABLE ICTUSER.USERS
(
	USERNAME varchar2(200 char) NOT NULL,
	NAME varchar2(20 char) NOT NULL,
	PASSWORD varchar2(50 char) NOT NULL,
	REGIDATE timestamp DEFAULT SYSDATE,
	GENDER varchar2(50) NOT NULL,
	INTER varchar2(100) NOT NULL,
	GRADE varchar2(100) NOT NULL,
	CONSTRAINT SYS_C007590 PRIMARY KEY (USERNAME)
);



/* Create Foreign Keys */

ALTER TABLE ICTUSER.BBS
	ADD CONSTRAINT SYS_C007591 FOREIGN KEY (USERNAME)
	REFERENCES ICTUSER.USERS (USERNAME)
;



